services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ultrabus-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD:-YourStrong@Passw0rd}
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - ultrabus-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '${DB_PASSWORD:-YourStrong@Passw0rd}' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # .NET API Backend với EF Migrations
  ultrabus-api:
    build:
      context: ./UltraBusAPI
      dockerfile: Dockerfile
    container_name: ultrabus-api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "${API_PORT:-5000}:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - ultrabus-network
    restart: unless-stopped

  # Admin Frontend (Next.js)
  ultrabus-admin:
    build:
      context: ./ultrabus-admin
      dockerfile: Dockerfile
    container_name: ultrabus-admin
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:5000}
    ports:
      - "${ADMIN_PORT:-3000}:3000"
    depends_on:
      - ultrabus-api
    networks:
      - ultrabus-network
    restart: unless-stopped

  # Web Frontend (Next.js)
  ultrabus-web:
    build:
      context: ./ultrabus-web
      dockerfile: Dockerfile
    container_name: ultrabus-web
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:5000}
    ports:
      - "${WEB_PORT:-3001}:3001"
    depends_on:
      - ultrabus-api
    networks:
      - ultrabus-network
    restart: unless-stopped

volumes:
  sqlserver_data:
    driver: local

networks:
  ultrabus-network:
    driver: bridge
