services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ultrabus-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: Express
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  # .NET API Backend
  ultrabus-api:
    build:
      context: ./UltraBusAPI
      dockerfile: Dockerfile
    container_name: ultrabus-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    restart: unless-stopped

  # Admin Frontend
  ultrabus-admin:
    build:
      context: ./ultrabus-admin
      dockerfile: Dockerfile
    container_name: ultrabus-admin
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    ports:
      - "8081:3000"
    depends_on:
      - ultrabus-api
    restart: unless-stopped

  # Web Frontend
  ultrabus-web:
    build:
      context: ./ultrabus-web
      dockerfile: Dockerfile
    container_name: ultrabus-web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    ports:
      - "8082:3001"
    depends_on:
      - ultrabus-api
    restart: unless-stopped

volumes:
  sqlserver_data:
